MyHotel/Controllers/BedRoomController.cs
using Microsoft.AspNet.Identity;
using MyHotel.Services;
using MyHotel.Services.Interfaces;
using MyHotel.ViewModel.BedRoom;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace MyHotel.Controllers
{
    [Authorize]
    public class BedRoomController : Controller
    {
        private IBedRoomService _BedRoomService;

        public BedRoomController(IBedRoomService bedRoomService)
        {
            _BedRoomService = bedRoomService;
        }

        // GET: BedRoom
        public ActionResult Index()
        {
            var model = _BedRoomService.GetAll();
            return View(model);
        }

        public ActionResult Table()
        {
            try
            {
                var model = _BedRoomService.GetAll();
                var view = CommonExtension.RenderRazorViewToString("_Table", model, this);

                return Json(new { error = false, result = view }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(new { error = true, result = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Create()
        {
            try
            {
                var Bed = _BedRoomService.GetById(0);
                var model = CommonExtension.RenderRazorViewToString("_CreateBedRoom", Bed, this);
                return Json(new { error = false, result = model }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { error = true, result = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public async Task<ActionResult> Create(BedRoomViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    CommonExtension.Currentuser = User.Identity.GetUserName();
                    int result = 0;
                    if (model.BedRoomID <= 0)
                        result = await _BedRoomService.Insert(model);
                    else
                        result = await _BedRoomService.Update(model);

                    return Json(new { error = false, result = "Registro guardado correctamente !" }, JsonRequestBehavior.AllowGet);
                }

                return Json(new { error = true, result = "Error en el modelo, favor validar los campos" }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                return Json(new { error = true, result = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Edit(int id)
        {
            try
            {
                var Bed = _BedRoomService.GetById(id);
                var model = CommonExtension.RenderRazorViewToString("_CreateBedRoom", Bed, this);
                return Json(new { error = false, result = model }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { error = true, result = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

    }
}

MyHotel/Controllers/CustomerController.cs
using Microsoft.AspNet.Identity;
using MyHotel.Services;
using MyHotel.Services.Interfaces;
using MyHotel.ViewModel.Customer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MyHotel.Controllers
{
    [Authorize]
    public class CustomerController : Controller
    {
        private ICustomerService _CustomerService;

        public CustomerController(ICustomerService customerService)
        {
            _CustomerService = customerService;
        }

        // GET: Customer
        public ActionResult Index()
        {
            var model = _CustomerService.GetAll();
            return View(model);
        }

        public ActionResult Table()
        {
            try
            {
                var model = _CustomerService.GetAll();
                var view = CommonExtension.RenderRazorViewToString("_Table", model, this);

                return Json(new { error = false, result = view }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(new { error = true, result = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Create()
        {
            try
            {
                var Bed = new CustomerViewModel();
                var model = CommonExtension.RenderRazorViewToString("_CreateCustomer", Bed, this);
                return Json(new { error = false, result = model }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { error = true, result = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public async Task<ActionResult> Create(CustomerViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    CommonExtension.Currentuser = User.Identity.GetUserName();
                    int result = 0;

                    if (model.CustomerID <= 0)
                        result = await _CustomerService.Insert(model);
                    else
                        result = await _CustomerService.Update(model);

                    return Json(new { error = false, result = "Registro guardado correctamente !" }, JsonRequestBehavior.AllowGet);
                }

                return Json(new { error = true, result = "Error en el modelo, favor validar los campos" }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                return Json(new { error = true, result = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Edit(int id)
        {
            try
            {
                var Bed = _CustomerService.GetById(id);
                var model = CommonExtension.RenderRazorViewToString("_CreateCustomer", Bed, this);
                return Json(new { error = false, result = model }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { error = true, result = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

    }
}

MyHotel/Controllers/LevelRoomController.cs
using Microsoft.AspNet.Identity;
using MyHotel.Services;
using MyHotel.Services.Interfaces;
using MyHotel.ViewModel.LevelRoom;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace MyHotel.Controllers
{
    [Authorize]
    public class LevelRoomController : Controller
    {
        ILevelRoomService _levelRoomService;

        public LevelRoomController(ILevelRoomService levelRoomService)
        {
            _levelRoomService = levelRoomService;
        }

        // GET: LivelRoom
        public ActionResult Index()
        {
            var model = _levelRoomService.GetAll();
            return View(model);
        }

        public ActionResult Table()
        {
            var model = _levelRoomService.GetAll();
            var view = CommonExtension.RenderRazorViewToString("Table", model, this);

            return Json(new { error = false, result = view }, JsonRequestBehavior.AllowGet);
        }


        // GET: LivelRoom/Create
        public ActionResult Create()
        {
            try
            {

                var Level = new LevelRoomViewModel();
               

                var model = CommonExtension.RenderRazorViewToString("_CreateLevelRoom", Level, this);
                return Json(new { error = false, result = model }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { error = true, result = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        // POST: LivelRoom/Create
        [HttpPost]
        public async Task<ActionResult> Create(LevelRoomViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    CommonExtension.Currentuser = User.Identity.GetUserName();
                    int result = 0;
                    if (model.LevelID <= 0)
                        result = await _levelRoomService.Insert(model);
                    else
                        result = await _levelRoomService.Update(model);

                    return Json(new { error = false, result = "Registro guardado correctamente !" }, JsonRequestBehavior.AllowGet);
                }

                return Json(new { error = true, result = "Error en el modelo, favor validar los campos" }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                return Json(new { error = true, result = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        // GET: LivelRoom/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {

                var Level = new LevelRoomViewModel();
                Level = _levelRoomService.GetById(id);

                var model = CommonExtension.RenderRazorViewToString("_CreateLevelRoom", Level, this);
                return Json(new { error = false, result = model }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { error = true, result = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        // POST: LivelRoom/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: LivelRoom/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: LivelRoom/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MyHotel/Controllers/TypeRoomController.cs
using Microsoft.AspNet.Identity;
using MyHotel.Services;
using MyHotel.Services.Interfaces;
using MyHotel.ViewModel.TypeRoom;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MyHotel.Controllers
{
    [Authorize]
    public class TypeRoomController : Controller
    {
        private ITypeRoomService _typeRoomService;

        public TypeRoomController(ITypeRoomService typeRoomService)
        {
            _typeRoomService = typeRoomService;
        }

        // GET: TypeRoom
        public ActionResult Index()
        {
            var model = _typeRoomService.GetAll();
            return View(model);
        }

        public ActionResult Table()
        {
            try
            {
                var model = _typeRoomService.GetAll();
                var view = CommonExtension.RenderRazorViewToString("_Table", model, this);

                return Json(new { error = false, result = view }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(new { error = true, result = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Create()
        {
            try
            {
                var Type = new TypeRoomViewModel();
                var model = CommonExtension.RenderRazorViewToString("_CreateTypeRoom", Type, this);
                return Json(new { error = false, result = model }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { error = true, result = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public async Task<ActionResult> Create(TypeRoomViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    CommonExtension.Currentuser = User.Identity.GetUserName();
                    int result = 0;
                    if (model.TypeRoomID <= 0)
                        result = await _typeRoomService.Insert(model);
                    else
                        result = await _typeRoomService.Update(model);

                    return Json(new { error = false, result = "Registro guardado correctamente !" }, JsonRequestBehavior.AllowGet);
                }

                return Json(new { error = true, result = "Error en el modelo, favor validar los campos" }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                return Json(new { error = true, result = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Edit(int id)
        {
            try
            {

                var Type = new TypeRoomViewModel();
                Type = _typeRoomService.GetById(id);

                var model = CommonExtension.RenderRazorViewToString("_CreateTypeRoom", Type, this);
                return Json(new { error = false, result = model }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { error = true, result = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        
        // GET: TypeRoom/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: TypeRoom/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MyHotel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Hotel</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Content/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet" href="~/Content/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/Content/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="~/Content/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Content/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/Content/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/Content/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="~/Content/plugins/summernote/summernote-bs4.css">

    <link rel="stylesheet" href="~/Content/plugins/toastr/toastr.min.css">

    <link rel="stylesheet" href="~/Content/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css">

    <!-- Select2 -->
    <link rel="stylesheet" href="~/Content/plugins/select2/css/select2.min.css">
    <link rel="stylesheet" href="~/Content/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css">

    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <link href="~/Content/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/Content/plugins/datatables-responsive/css/responsive.bootstrap4.min.css" rel="stylesheet" />

    <link href="~/Content/dist/css/site.css" rel="stylesheet" />
</head>
<body class="hold-transition sidebar-mini layout-fixed">


    <div id="loader"></div>
    <div class="wrapper">
        <!-- Navbar -->
        @Html.Partial("_NavBar")
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        @Html.Partial("_SideBar")

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    @RenderBody()
                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->

        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <strong>Copyright &copy; 2020-2021 <a href="http://adminlte.io">Stanley Feliz</a>.</strong>
            All rights reserved.
            <div class="float-right d-none d-sm-inline-block">
                <b>Version</b> 1.0.0
            </div>
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/Content/plugins/jquery/jquery.min.js"></script>

    <!-- jQuery UI 1.11.4 -->
    <script src="~/Content/plugins/jquery-ui/jquery-ui.min.js"></script>

    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>

    <!-- Bootstrap 4 -->
    <script src="~/Content/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

    <script src="~/Content/plugins/select2/js/select2.full.min.js"></script>

    <!-- ChartJS -->
   @* <script src="~/Content/plugins/chart.js/Chart.min.js"></script>*@

    <!-- Sparkline -->
    @*<script src="~/Content/plugins/sparklines/sparkline.js"></script>*@

    <!-- JQVMap -->
    @*<script src="~/Content/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="~/Content/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>*@

    <!-- jQuery Knob Chart -->
    @*<script src="~/Content/plugins/jquery-knob/jquery.knob.min.js"></script>*@

    <!-- daterangepicker -->
    <script src="~/Content/plugins/moment/moment.min.js"></script>
    <script src="~/Content/plugins/daterangepicker/daterangepicker.js"></script>

    <!-- Tempusdominus Bootstrap 4 -->
    @*<script src="~/Content/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>*@

    <!-- Summernote -->
    @*<script src="~/Content/plugins/summernote/summernote-bs4.min.js"></script>*@

    <!-- overlayScrollbars -->
    <script src="~/Content/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>

    <script src="~/Content/plugins/sweetalert2/sweetalert2.min.js"></script>
    <script src="~/Content/plugins/toastr/toastr.min.js"></script>

    <!-- AdminLTE App -->
    <script src="~/Content/dist/js/adminlte.js"></script>

    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    @*<script src="~/Content/dist/js/pages/dashboard.js"></script>*@

    <!-- AdminLTE for demo purposes -->
    <script src="~/Content/dist/js/demo.js"></script>

    <script src="~/Content/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Content/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/Content/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/Content/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>

    <script src="~/Content/plugins/jquery-validation/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    <script src="~/Content/dist/js/site.js"></script>
    <script>
        var urlBase = '@Url.Content("~/")';
    </script>
    @RenderSection("scripts", required: false)

</body>
</html>

MyHotel/Views/Shared/_NavBar.cshtml
@using Microsoft.AspNet.Identity

<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
        <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-user-circle"></i> Hola <strong>@User.Identity.GetUserName()</strong>
                @*<span class="badge badge-warning navbar-badge">15</span>*@
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                {
                    @Html.AntiForgeryToken()

                    <a href="javascript:document.getElementById('logoutForm').submit()" class="dropdown-item">
                        <i class="fas fa-power-off mr-2"></i> Log off
                    </a>
                }
                <a href="@Url.Action("ChangePassword","Manage")" class="dropdown-item">
                    <i class="fas fa-lock mr-2"></i> Cambiar Contraseña
                </a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                <i class="fas fa-th-large"></i>
            </a>
        </li>
    </ul>
</nav>

MyHotel/Views/Shared/_SideBar.cshtml
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
        <img src="~/Content/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="~/Content/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">@Session["Nombre"]</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
    with font-awesome or any other icon font library menu-open -->
                <li class="nav-item">
                    <a href="#" class="nav-link active">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Dashboard
                            @*<i class="right fas fa-angle-left"></i>*@
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="@Url.Action("Index","Receptions")" class="nav-link">
                        <i class="fas fa-users"></i>
                        <p>Recepción</p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="@Url.Action("Index","Customer")" class="nav-link">
                        <i class="fas fa-users"></i>
                        <p>Clientes</p>
                    </a>
                </li>

                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-toolbox"></i>
                        <p>
                            Mantenimiento
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">

                        <li class="nav-item">
                            <a href="@Url.Action("Index","BedRoom")" class="nav-link">
                                <i class="fas fa-bed"></i>
                                <p>Habitaciones</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index","TypeRoom")" class="nav-link">
                                <i class="fas fa-person-booth"></i>
                                <p>Tipos de Habitaciones</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index","LevelRoom")" class="nav-link">
                                <i class="fas fa-list-ol nav-icon"></i>
                                <p>Pisos</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index","Account")" class="nav-link">
                                <i class="fas fa-users nav-icon"></i>
                                <p>Usuarios</p>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>